//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseInfo.UserApp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ExcelSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ExcelSettings defaultInstance = ((ExcelSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ExcelSettings())));
        
        public static ExcelSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("лист запрос")]
        public string WorksheetNameInCalc {
            get {
                return ((string)(this["WorksheetNameInCalc"]));
            }
            set {
                this["WorksheetNameInCalc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tab1")]
        public string WorksheetFlatsNameInBD {
            get {
                return ((string)(this["WorksheetFlatsNameInBD"]));
            }
            set {
                this["WorksheetFlatsNameInBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tab2")]
        public string WorksheetHousesNameInBD {
            get {
                return ((string)(this["WorksheetHousesNameInBD"]));
            }
            set {
                this["WorksheetHousesNameInBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B-F")]
        public string AddressColumnsInFlats {
            get {
                return ((string)(this["AddressColumnsInFlats"]));
            }
            set {
                this["AddressColumnsInFlats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A32-E32")]
        public string AddressInCalc {
            get {
                return ((string)(this["AddressInCalc"]));
            }
            set {
                this["AddressInCalc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A36-B36 = G-H; C36-Q36 = N-AB; B39-Q39 = AC-AR; E43 = A;")]
        public string СopiedIntervalsToFlatsWorksheet {
            get {
                return ((string)(this["СopiedIntervalsToFlatsWorksheet"]));
            }
            set {
                this["СopiedIntervalsToFlatsWorksheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A43-R43 = A-R;")]
        public string СopiedIntervalsToHousesWorksheet {
            get {
                return ((string)(this["СopiedIntervalsToHousesWorksheet"]));
            }
            set {
                this["СopiedIntervalsToHousesWorksheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int FlatsBeginTableRow {
            get {
                return ((int)(this["FlatsBeginTableRow"]));
            }
            set {
                this["FlatsBeginTableRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int FlatsStartRow {
            get {
                return ((int)(this["FlatsStartRow"]));
            }
            set {
                this["FlatsStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int HousesBeginRow {
            get {
                return ((int)(this["HousesBeginRow"]));
            }
            set {
                this["HousesBeginRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HousesStartRow {
            get {
                return ((int)(this["HousesStartRow"]));
            }
            set {
                this["HousesStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NonDublicateHouses {
            get {
                return ((bool)(this["NonDublicateHouses"]));
            }
            set {
                this["NonDublicateHouses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D-H")]
        public string AddressColumnsInHouses {
            get {
                return ((string)(this["AddressColumnsInHouses"]));
            }
            set {
                this["AddressColumnsInHouses"] = value;
            }
        }
    }
}
